version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: e-demokrasi-python
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app